import { FastifyInstance, FastifyPluginOptions } from 'fastify';
import { UserController } from '../controllers/user.controller.js';

export default async function userRoutes(
  fastify: FastifyInstance,
  options: FastifyPluginOptions
): Promise<void> {
  const userController = new UserController();

  // Swagger tags for grouping
  const swaggerTags = ['Users'];

  // Create User
  fastify.post('/', {
    schema: {
      tags: swaggerTags,
      summary: 'Create a new user',
      description: 'Create a new user with all required information. Password will be automatically hashed. The _id field will be auto-generated by MongoDB.',
      body: {
        type: 'object',
        required: ['name', 'email', 'password'],
        properties: {
          name: { 
            type: 'string', 
            minLength: 2, 
            maxLength: 100, 
            description: 'User full name (supports Arabic)'
          },
          email: { 
            type: 'string', 
            format: 'email', 
            description: 'Unique email address'
          },
          password: { 
            type: 'string', 
            minLength: 6, 
            maxLength: 128, 
            description: 'Password (will be automatically hashed)'
          },
          role: { 
            type: 'string', 
            enum: ['admin', 'manager', 'sales_rep'], 
            default: 'sales_rep',
            description: 'User role (defaults to sales_rep if not specified)'
          },
          managerId: { 
            type: 'string', 
            pattern: '^[0-9a-fA-F]{24}$',
            description: 'MongoDB ObjectId of manager (optional)'
          },
          managerName: { 
            type: 'string', 
            minLength: 2, 
            maxLength: 100,
            description: 'Manager name (optional, supports Arabic)'
          }
        }
      },
      response: {
        201: {
          description: 'User created successfully',
          type: 'object',
          properties: {
            success: { type: 'boolean', example: true },
            message: { type: 'string', example: 'User created successfully.' },
            data: {
              type: 'object',
              properties: {
                _id: { 
                  type: 'string', 
                  description: 'Auto-generated MongoDB ObjectId',
                  example: '64a7b8c9d1e2345f67890123'
                },
                name: { type: 'string', example: 'محمد عبدالله' },
                email: { type: 'string', example: 'mohammed.abdullah@company.com' },
                role: { type: 'string', enum: ['admin', 'manager', 'sales_rep'], example: 'sales_rep' },
                managerId: { type: 'string', nullable: true, example: null },
                managerName: { type: 'string', nullable: true, example: null },
                createdAt: { type: 'string', format: 'date-time', example: '2024-01-15T13:30:00.000Z' },
                updatedAt: { type: 'string', format: 'date-time', example: '2024-01-15T13:30:00.000Z' }
              }
            },
            timestamp: { type: 'string', example: '2024-01-15 16:30:00' }
          }
        },
        400: {
          description: 'Bad Request - Invalid input data',
          type: 'object',
          properties: {
            success: { type: 'boolean', example: false },
            message: { type: 'string', example: 'Validation failed' },
            error: {
              type: 'object',
              properties: {
                code: { type: 'string', example: 'VALIDATION_ERROR' },
                message: { type: 'string', example: 'The provided data is invalid' }
              }
            },
            timestamp: { type: 'string', example: '2024-01-15 16:30:00' }
          }
        },
        409: {
          description: 'Conflict - Email already exists',
          type: 'object',
          properties: {
            success: { type: 'boolean', example: false },
            message: { type: 'string', example: 'Email already exists' },
            error: {
              type: 'object',
              properties: {
                code: { type: 'string', example: 'EMAIL_ALREADY_EXISTS' },
                message: { type: 'string', example: 'A user with this email address already exists' }
              }
            },
            timestamp: { type: 'string', example: '2024-01-15 16:30:00' }
          }
        }
      }
    },
    handler: userController.createUser.bind(userController)
  });

  // Get All Users
  fastify.get('/', {
    schema: {
      tags: swaggerTags,
      summary: 'Get all users with dynamic filtering',
      description: `
Retrieve users with powerful filtering capabilities:

**Dynamic Filtering**: Filter by any user field (name, email, role, managerId, managerName, etc.)
**Text Search**: Use 'search' parameter to search across name, email, and managerName
**Pagination**: Control page size and navigation
**Sorting**: Sort by any field in ascending or descending order

**Examples:**
- Get users with role 'sales_rep': \`/users?role=sales_rep\`
- Search for users by name: \`/users?name=محمد\`
- Get users by manager: \`/users?managerId=64a7b8c9d1e2345f67890123\`
- Combined filters: \`/users?role=manager&name=ahmed&page=2\`
- Text search: \`/users?search=محمد\`
      `,
      querystring: {
        type: 'object',
        properties: {
          page: { 
            type: 'integer', 
            minimum: 1, 
            default: 1,
            description: 'Page number for pagination (starts from 1)'
          },
          limit: { 
            type: 'integer', 
            minimum: 1, 
            maximum: 100, 
            default: 10,
            description: 'Number of items per page (max 100)'
          },
          sort: { 
            type: 'string', 
            default: 'createdAt',
            enum: ['name', 'email', 'role', 'createdAt', 'updatedAt'],
            description: 'Field to sort by'
          },
          order: { 
            type: 'string', 
            enum: ['asc', 'desc'], 
            default: 'desc',
            description: 'Sort order: ascending or descending'
          },
          search: { 
            type: 'string',
            description: 'Search text across name, email, and managerName fields'
          },
          name: { 
            type: 'string',
            description: 'Filter by user name (case-insensitive partial match)'
          },
          email: { 
            type: 'string',
            description: 'Filter by email address (case-insensitive partial match)'
          },
          role: { 
            type: 'string',
            enum: ['admin', 'manager', 'sales_rep'],
            description: 'Filter by user role'
          },
          managerId: { 
            type: 'string',
            pattern: '^[0-9a-fA-F]{24}$',
            description: 'Filter by manager ID (exact match)'
          },
          managerName: { 
            type: 'string',
            description: 'Filter by manager name (case-insensitive partial match)'
          },
          createdAt: {
            type: 'string',
            format: 'date-time',
            description: 'Filter by creation date (ISO format)'
          },
          updatedAt: {
            type: 'string',
            format: 'date-time',
            description: 'Filter by last update date (ISO format)'
          }
        }
      },
      response: {
        200: {
          description: 'Users retrieved successfully',
          type: 'object',
          properties: {
            success: { type: 'boolean', example: true },
            message: { type: 'string', example: 'Users retrieved successfully.' },
            data: {
              type: 'object',
              properties: {
                data: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      _id: { type: 'string', example: '64a7b8c9d1e2345f67890123' },
                      name: { type: 'string', example: 'محمد عبدالله' },
                      email: { type: 'string', example: 'mohammed.abdullah@company.com' },
                      role: { type: 'string', enum: ['admin', 'manager', 'sales_rep'], example: 'sales_rep' },
                      managerId: { type: 'string', nullable: true, example: '64a7b8c9d1e2345f67890456' },
                      managerName: { type: 'string', nullable: true, example: 'سارة أحمد' },
                      createdAt: { type: 'string', format: 'date-time', example: '2024-01-15T13:30:00.000Z' },
                      updatedAt: { type: 'string', format: 'date-time', example: '2024-01-15T13:30:00.000Z' }
                    }
                  }
                },
                pagination: {
                  type: 'object',
                  properties: {
                    currentPage: { type: 'integer', example: 1 },
                    totalPages: { type: 'integer', example: 5 },
                    totalItems: { type: 'integer', example: 47 },
                    itemsPerPage: { type: 'integer', example: 10 },
                    hasNextPage: { type: 'boolean', example: true },
                    hasPrevPage: { type: 'boolean', example: false }
                  }
                }
              }
            },
            timestamp: { type: 'string', example: '2024-01-15 16:30:00' }
          }
        }
      }
    },
    handler: userController.getUsers.bind(userController)
  });

  // Get User by ID
  fastify.get('/:id', {
    schema: {
      tags: swaggerTags,
      summary: 'Get user by ID',
      description: 'Retrieve a specific user by their unique MongoDB ObjectId.',
      params: {
        type: 'object',
        required: ['id'],
        properties: {
          id: { 
            type: 'string',
            pattern: '^[0-9a-fA-F]{24}$',
            description: 'MongoDB ObjectId of the user'
          }
        }
      },
      response: {
        200: {
          description: 'User retrieved successfully',
          type: 'object',
          properties: {
            success: { type: 'boolean', example: true },
            message: { type: 'string', example: 'User retrieved successfully.' },
            data: {
              type: 'object',
              properties: {
                _id: { type: 'string', example: '64a7b8c9d1e2345f67890123' },
                name: { type: 'string', example: 'فاطمة أحمد' },
                email: { type: 'string', example: 'fatima.ahmed@company.com' },
                role: { type: 'string', enum: ['admin', 'manager', 'sales_rep'], example: 'manager' },
                managerId: { type: 'string', nullable: true, example: null },
                managerName: { type: 'string', nullable: true, example: null },
                createdAt: { type: 'string', format: 'date-time', example: '2024-01-15T13:30:00.000Z' },
                updatedAt: { type: 'string', format: 'date-time', example: '2024-01-15T13:30:00.000Z' }
              }
            },
            timestamp: { type: 'string', example: '2024-01-15 16:30:00' }
          }
        },
        404: {
          description: 'User not found',
          type: 'object',
          properties: {
            success: { type: 'boolean', example: false },
            message: { type: 'string', example: 'User not found with the specified ID' },
            error: {
              type: 'object',
              properties: {
                code: { type: 'string', example: 'USER_NOT_FOUND' },
                message: { type: 'string', example: 'No user exists with the provided ID' }
              }
            },
            timestamp: { type: 'string', example: '2024-01-15 16:30:00' }
          }
        }
      }
    },
    handler: userController.getUserById.bind(userController)
  });

  // Update User
  fastify.put('/:id', {
    schema: {
      tags: swaggerTags,
      summary: 'Update user by ID',
      description: 'Update an existing user. Only provided fields will be updated. Password will be automatically hashed if provided. The updatedAt timestamp will be automatically updated.',
      params: {
        type: 'object',
        required: ['id'],
        properties: {
          id: { 
            type: 'string',
            pattern: '^[0-9a-fA-F]{24}$',
            description: 'MongoDB ObjectId of the user'
          }
        }
      },
      body: {
        type: 'object',
        properties: {
          name: { 
            type: 'string', 
            minLength: 2, 
            maxLength: 100,
            description: 'Updated user name'
          },
          email: { 
            type: 'string', 
            format: 'email',
            description: 'Updated email address'
          },
          password: { 
            type: 'string', 
            minLength: 6, 
            maxLength: 128,
            description: 'New password (will be hashed automatically)'
          },
          role: { 
            type: 'string', 
            enum: ['admin', 'manager', 'sales_rep'],
            description: 'Updated user role'
          },
          managerId: { 
            type: 'string', 
            pattern: '^[0-9a-fA-F]{24}$',
            description: 'Updated manager ID'
          },
          managerName: { 
            type: 'string', 
            minLength: 2, 
            maxLength: 100,
            description: 'Updated manager name'
          }
        }
      }
    },
    handler: userController.updateUser.bind(userController)
  });

  // Delete User
  fastify.delete('/:id', {
    schema: {
      tags: swaggerTags,
      summary: 'Delete user by ID',
      description: 'Permanently delete a user. This action cannot be undone.',
      params: {
        type: 'object',
        required: ['id'],
        properties: {
          id: { 
            type: 'string',
            pattern: '^[0-9a-fA-F]{24}$',
            description: 'MongoDB ObjectId of the user'
          }
        }
      }
    },
    handler: userController.deleteUser.bind(userController)
  });

  // Get Users by Manager
  fastify.get('/manager/:managerId', {
    schema: {
      tags: swaggerTags,
      summary: 'Get users by manager ID',
      description: 'Get all users managed by a specific manager. Supports additional filtering and pagination.',
      params: {
        type: 'object',
        required: ['managerId'],
        properties: {
          managerId: { 
            type: 'string',
            pattern: '^[0-9a-fA-F]{24}$',
            description: 'MongoDB ObjectId of the manager'
          }
        }
      },
      querystring: {
        type: 'object',
        properties: {
          page: { type: 'integer', minimum: 1, default: 1 },
          limit: { type: 'integer', minimum: 1, maximum: 100, default: 10 },
          sort: { type: 'string', default: 'createdAt' },
          order: { type: 'string', enum: ['asc', 'desc'], default: 'desc' },
          search: { type: 'string' },
          name: { type: 'string' },
          email: { type: 'string' },
          role: { type: 'string', enum: ['admin', 'manager', 'sales_rep'] }
        }
      }
    },
    handler: userController.getUsersByManager.bind(userController)
  });

  // Get User Statistics
  fastify.get('/stats', {
    schema: {
      tags: swaggerTags,
      summary: 'Get user statistics',
      description: 'Get comprehensive statistics about users including total counts and distribution by role.',
      response: {
        200: {
          description: 'User statistics retrieved successfully',
          type: 'object',
          properties: {
            success: { type: 'boolean', example: true },
            message: { type: 'string', example: 'User statistics retrieved successfully.' },
            data: {
              type: 'object',
              properties: {
                totalUsers: { type: 'integer', example: 150, description: 'Total number of users' },
                usersByRole: {
                  type: 'object',
                  properties: {
                    admin: { type: 'integer', example: 5, description: 'Number of admin users' },
                    manager: { type: 'integer', example: 15, description: 'Number of manager users' },
                    sales_rep: { type: 'integer', example: 130, description: 'Number of sales rep users' }
                  }
                },
                distinctRoles: {
                  type: 'array',
                  items: { type: 'string' },
                  example: ['admin', 'manager', 'sales_rep'],
                  description: 'List of all roles in the system'
                },
                generatedAt: { type: 'string', format: 'date-time', example: '2024-01-15T13:30:00.000Z' }
              }
            },
            timestamp: { type: 'string', example: '2024-01-15 16:30:00' }
          }
        }
      }
    },
    handler: userController.getUserStats.bind(userController)
  });

  // Get Users by Role
  fastify.get('/role/:role', {
    schema: {
      tags: swaggerTags,
      summary: 'Get users by role',
      description: 'Get all users with a specific role. Supports additional filtering and pagination.',
      params: {
        type: 'object',
        required: ['role'],
        properties: {
          role: { 
            type: 'string',
            enum: ['admin', 'manager', 'sales_rep'],
            description: 'User role to filter by'
          }
        }
      },
      querystring: {
        type: 'object',
        properties: {
          page: { type: 'integer', minimum: 1, default: 1 },
          limit: { type: 'integer', minimum: 1, maximum: 100, default: 10 },
          sort: { type: 'string', default: 'createdAt' },
          order: { type: 'string', enum: ['asc', 'desc'], default: 'desc' },
          search: { type: 'string' },
          name: { type: 'string' },
          email: { type: 'string' },
          managerId: { type: 'string', pattern: '^[0-9a-fA-F]{24}$' },
          managerName: { type: 'string' }
        }
      }
    },
    handler: userController.getUsersByRole.bind(userController)
  });

  // Advanced Search Route
  fastify.post('/search/advanced', {
    schema: {
      tags: swaggerTags,
      summary: 'Advanced user search',
      description: `
Perform advanced search with complex conditions and operators for precise filtering.

**Supported Operators:**
- \`eq\`: Equal to
- \`ne\`: Not equal to  
- \`gt\`: Greater than
- \`gte\`: Greater than or equal to
- \`lt\`: Less than
- \`lte\`: Less than or equal to
- \`in\`: In array of values
- \`nin\`: Not in array of values
- \`regex\`: Regular expression match

**Example Request:**
\`\`\`json
{
  "conditions": [
    { "field": "role", "operator": "eq", "value": "sales_rep" },
    { "field": "name", "operator": "regex", "value": "محمد" }
  ],
  "pagination": { "page": 1, "limit": 10 }
}
\`\`\`
      `,
      body: {
        type: 'object',
        required: ['conditions'],
        properties: {
          conditions: {
            type: 'array',
            items: {
              type: 'object',
              required: ['field', 'operator', 'value'],
              properties: {
                field: { 
                  type: 'string', 
                  description: 'Field name to search in'
                },
                operator: { 
                  type: 'string', 
                  enum: ['eq', 'ne', 'gt', 'gte', 'lt', 'lte', 'in', 'nin', 'regex'],
                  description: 'Comparison operator'
                },
                value: { 
                  description: 'Value to compare against (type depends on field)'
                }
              }
            },
            minItems: 1,
            description: 'Array of search conditions'
          },
          pagination: {
            type: 'object',
            properties: {
              page: { type: 'integer', minimum: 1, default: 1 },
              limit: { type: 'integer', minimum: 1, maximum: 100, default: 10 },
              sort: { type: 'string', default: 'createdAt' },
              order: { type: 'string', enum: ['asc', 'desc'], default: 'desc' }
            }
          }
        }
      }
    },
    handler: userController.advancedSearch.bind(userController)
  });
} 