export enum TaskStatus {
  PENDING = 'PENDING', // Task is recommended by the system, awaiting manager review.
  TODO = 'TODO', // Manager has approved and scheduled the task.
  IN_PROGRESS = 'IN_PROGRESS', // Agent has started the task.
  COMPLETED = 'COMPLETED', // Agent has completed the task.
  CANCELLED = 'CANCELLED', // Manager or system has cancelled the task.
  FAILED = 'FAILED', // Agent attempted the task but could not complete it.
}




export enum TaskPriority {
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum TaskType {
  DELIVERY = 'DELIVERY',
  NEW_SALES = 'NEW_SALES',
  SALES_VISIT = 'SALES_VISIT',
  STOCK_RECONCILIATION = 'STOCK_RECONCILIATION',
  NEW_OUTLET_ONBOARDING = 'NEW_OUTLET_ONBOARDING',
  OTHER = 'OTHER',
}

export enum TaskSource {
  MANUAL = 'MANUAL', // Created by a manager.
  ENTITLEMENT = 'ENTITLEMENT', // Generated from a recurring entitlement.
  SYSTEM = 'SYSTEM', // Generated by other system processes (e.g., low stock alert).
}

export interface ITaskComment {
  user: string | Object; // userId - can be string or ObjectId
  userName: string;
  comment: string;
  timestamp: Date;
}

export interface ITask extends Document {
  title: string;
  details?: string;
  status: TaskStatus;
  type: TaskType;
  priority: TaskPriority;
  source: TaskSource;
  assignedTo?: string; // Agent's userId
  assignedBy?: string; // Manager's userId
  accountId?: string; // Link to the Account
  orderId?: string; // Link to the resulting Order
  orderEntitlementId?: string; // Link to the source Entitlement
  dueDate: Date;
  scheduledDate?: Date;
  completedDate?: Date;
  comments: ITaskComment[];
  updatedAt: Date;
}

export interface ITaskCreate extends Omit<ITask, 'status' | 'comments' | 'source'> {
  // Status and source are set by the system/service logic.
}

export interface ITaskUpdate {
  title?: string;
  details?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  assignedTo?: string;
  dueDate?: Date;
  scheduledDate?: Date;
}

export interface ITaskStatusUpdate {
  status: TaskStatus;
  comment: string;
}

export interface ITaskQuery {
  status?: TaskStatus;
  type?: TaskType;
  priority?: TaskPriority;
  assignedTo?: string;
  assignedBy?: string;
  accountId?: string;
  dueDateFrom?: Date;
  dueDateTo?: Date;
}

export interface ITaskInput {
  title: string;
  details?: string;
  type: TaskType;
  priority: TaskPriority;
  assignedTo?: string;
  accountId?: string; // Optional account ID reference
  dueDate: Date;
  scheduledDate?: Date;
} 